export const ALL_RECORDS = 'ALL_RECORDS';
export const ALL_RECORDS_ERROR = 'ALL_RECORDS_ERROR';
export const GET_SINGLE_RECORD = 'GET_SINGLE_RECORD';
export const GET_SINGLE_RECORD_ERROR = 'GET_SINGLE_RECORD_ERROR';
